#include "stm32f10x.h"

extern const uint32_t __GPIO_PORT_BASEs[] = {GPIOA_BASE, GPIOB_BASE, GPIOC_BASE, GPIOD_BASE};
extern const uint32_t __GPIO_PORT_RCC_EN[] = {RCC_APB2ENR_IOPAEN, RCC_APB2ENR_IOPBEN, RCC_APB2ENR_IOPCEN, RCC_APB2ENR_IOPDEN};

extern const uint32_t __USART_BASEs[] = {USART1_BASE, USART2_BASE, USART3_BASE, UART4_BASE, UART5_BASE};
extern const uint32_t __USART_RCC_EN[] = {RCC_APB2ENR_USART1EN, RCC_APB1ENR_USART2EN, RCC_APB1ENR_USART3EN, RCC_APB1ENR_UART4EN, RCC_APB1ENR_UART5EN};
extern uint32_t const __USART_RCC_ENR_BASEs[] = {RCC_BASE + 0x18, RCC_BASE + 0x1c, RCC_BASE + 0x1c, RCC_BASE + 0x1c};

extern const uint32_t __DMA_BASEs[] = {DMA1_BASE, DMA2_BASE};
extern const uint32_t __DMA_RCC_EN[] = {RCC_AHBENR_DMA1EN, RCC_AHBENR_DMA2EN};
extern uint32_t const __DMA_RCC_ENR_BASEs[] = {RCC_BASE + 0x14, RCC_BASE + 0x14};

extern const uint32_t __ADC_BASEs[] = {ADC1_BASE, ADC2_BASE, ADC3_BASE};
extern const uint32_t __ADC_RCC_EN[] = {RCC_APB2ENR_ADC1EN, RCC_APB2ENR_ADC2EN, RCC_APB2ENR_ADC3EN};
extern uint32_t const __ADC_RCC_ENR_BASEs[] = {RCC_BASE + 0x18, RCC_BASE + 0x18, RCC_BASE + 0x18};
