// #include "stm32f10x.h"
#include "chipf10x.hpp"

#define RCC_AHB_ENR_ADDRESS (RCC_BASE + 0x14)
#define RCC_APB1_ENR_ADDRESS (RCC_BASE + 0x1c)
#define RCC_APB2_ENR_ADDRESS (RCC_BASE + 0x18)

const uint32_t __GPIO_PORT_BASEs[] = {GPIOA_BASE, GPIOB_BASE, GPIOC_BASE, GPIOD_BASE};
const uint32_t __GPIO_PORT_RCC_EN[] = {RCC_APB2ENR_IOPAEN, RCC_APB2ENR_IOPBEN, RCC_APB2ENR_IOPCEN, RCC_APB2ENR_IOPDEN};

const uint32_t __USART_BASEs[] = {USART1_BASE, USART2_BASE, USART3_BASE, UART4_BASE, UART5_BASE};
const uint32_t __USART_RCC_EN[] = {RCC_APB2ENR_USART1EN, RCC_APB1ENR_USART2EN, RCC_APB1ENR_USART3EN, RCC_APB1ENR_UART4EN, RCC_APB1ENR_UART5EN};
uint32_t const __USART_RCC_ENR_BASEs[] = {RCC_APB2_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS};

const uint32_t __DMA_BASEs[] = {DMA1_BASE, DMA2_BASE};
const uint32_t __DMA_RCC_EN[] = {RCC_AHBENR_DMA1EN, RCC_AHBENR_DMA2EN};
uint32_t const __DMA_RCC_ENR_BASEs[] = {RCC_AHB_ENR_ADDRESS, RCC_AHB_ENR_ADDRESS};

const uint32_t __ADC_BASEs[] = {ADC1_BASE, ADC2_BASE, ADC3_BASE};
const uint32_t __ADC_RCC_EN[] = {RCC_APB2ENR_ADC1EN, RCC_APB2ENR_ADC2EN, RCC_APB2ENR_ADC3EN};
uint32_t const __ADC_RCC_ENR_BASEs[] = {RCC_APB2_ENR_ADDRESS, RCC_APB2_ENR_ADDRESS, RCC_APB2_ENR_ADDRESS};

const uint32_t __SPI_BASEs[] = {SPI1_BASE, SPI2_BASE, SPI3_BASE};
const uint32_t __SPI_RCC_EN[] = {RCC_APB2ENR_SPI1EN, RCC_APB1ENR_SPI2EN, RCC_APB1ENR_SPI3EN};
uint32_t const __SPI_RCC_ENR_BASEs[] = {RCC_APB2_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS};

const uint32_t __TIM_BASEs[] = {TIM1_BASE, TIM2_BASE, TIM3_BASE, TIM4_BASE, TIM5_BASE, TIM6_BASE, TIM7_BASE, TIM8_BASE}; //, TIM9_BASE, TIM10_BASE, TIM11_BASE, TIM12_BASE, TIM13_BASE, TIM14_BASE, TIM15_BASE, TIM16_BASE, TIM17_BASE};
const uint32_t __TIM_RCC_EN[] = {
    RCC_APB2ENR_TIM1EN, RCC_APB1ENR_TIM2EN,
    RCC_APB1ENR_TIM3EN, RCC_APB1ENR_TIM4EN,
    RCC_APB1ENR_TIM5EN, RCC_APB1ENR_TIM6EN,
    RCC_APB1ENR_TIM7EN, RCC_APB2ENR_TIM8EN};
uint32_t const __TIM_RCC_ENR_BASEs[] = {
    RCC_APB2_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS,
    RCC_APB1_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS,
    RCC_APB1_ENR_ADDRESS, RCC_APB1_ENR_ADDRESS,
    RCC_APB1_ENR_ADDRESS, RCC_APB2_ENR_ADDRESS};
